name: Build Windows Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build application
      run: bun run make
      
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: league-tools-windows
        path: out/
        include-hidden-files: true
        retention-days: 30
